
name: Azure App Service - TeamCheckFrontend, Build and deploy Vue frontend in node

env:
  NODE_VERSION: '14.x'                # set this to the node version to use

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and deploy
    environment: production
    runs-on: ubuntu-latest

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@main

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install dependencies with npm
      run: npm install

    - name: Build with npm
      run: npm run build --if-present

    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: jacob-team-check
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A16C84AA282E4D59AB88D41E8D4F61BD }}
        package: ./dist
